### ISSUE TITLE
Allow specify Admins

### ISSUE THREAD

**Issue by rtholmes** [asalahli/se2#1]
in `settings.json` maybe something like:

```
admins: [
  {
    github: 'uname',
    name: 'Name',
    role: 'prof/ta'
  },
  {
    github: 'uname',
    name: 'Name',
    role: 'prof/ta'
  }
]
```

This would still allow the normal github authentication to be used. This would also mean once you come back to `http://localhost:3000/register?github=rtholmes` you could check to see if they were in admins and just spit them to the admin interface instead of getting them to associate with a student id.

**Comment by asalahli** [comment]
Done!
